// // import { Geist, Geist_Mono } from "next/font/google";
// // import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
// // import { ThemeProvider } from '@mui/material/styles';
// // import "./globals.css";
// // import theme from "../theme"
// // import Navigation from "./components/Navigation";
// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //        <AppRouterCacheProvider>
// //            <ThemeProvider theme={theme}>
// //            <Navigation className=" top-0 left-0 right-0 z-50"/>

// //            <div className=" min-h-screen">
// //               {children}   
// //            </div>
            
// //               <footer className="text-center">
// //                 <p>2025 @ Sohan Achhami.</p>
// //                 </footer>
// //            </ThemeProvider>
// //           </AppRouterCacheProvider>
        
// //       </body>
// //     </html>
// //   );
// // }
// import { Geist, Geist_Mono } from "next/font/google";
// import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
// import { ThemeProvider } from "@mui/material/styles";
// import "./globals.css";
// import theme from "../theme";
// import Navigation from "./components/Navigation";

// const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
// const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <AppRouterCacheProvider>
//           <ThemeProvider theme={theme}>
//             {/* Navbar over hero: absolute + on top */}
//             <Navigation className="absolute top-0 left-0 right-0 z-50 text-white" />
//             <div className="min-h-screen">
//              {children}
//             </div>
         

//             <footer className="text-center py-6">
//               <p>2025 @ Sohan Achhami.</p>
//             </footer>
//           </ThemeProvider>
//         </AppRouterCacheProvider>
//       </body>
//     </html>
//   );
// }
import { Geist, Geist_Mono } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import "./globals.css";
import theme from "../theme";
import Navigation from "./components/Navigation/Navigation";
import Footer from "./components/Footer/footer";


const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            {/* ✅ Fixed navbar now */}
            <Navigation className="fixed top-0 left-0 right-0  text-white bg-transparent" />

            {/* Add padding-top so content isn't hidden behind navbar */}
            <div className="pt-24 min-h-screen">
              {children}
            </div>
            <Footer/>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
